config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/invites', to: 'invites#show'
  root to: "homes#show"

  resources :sessions, only: [:create, :destroy]
  resource :homes, only: [:show]
  resources :search, only: [:index]
  resource :mate_preference, only: [:update]
  resource :trait, only: [:update]

  resources :conversations do
    resources :messages
   end

   resources :daters do 
    resources :images
  end
  resources :dashboard

  resources :backers do
    resources :daters do
          resources :comments,  as: 'comments'
          resources :personalities
    end
  end

  resources :users
  post 'search', to: 'search#create' , as: "search"

  get 'user/:id/pool', to: 'pool#index' , as: "user_pool"
  put 'user/:id/pool', to: 'pool#update' , as: "edit_user_pool"


  namespace :api do
    namespace :v1 do

      resources :users, only: [:index, :show]

      resources :daters, only: [:index, :show]
      namespace :daters do
        get "/:id/backers", to: "backers#index"
        get "/:id/backers/:backer_id", to: "backers#create"
        # post "/meals/:meal_id/foods/:id", to: "meals#create", as: :meal_foods
      end

      resources :backers, only: [:index, :show]
      namespace :backers do
        get "/:id/daters", to: "daters#index"
      end

    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    
    def show
    end
  end
  

app/views/dashboard/_add_backer.html.erb
<div class="search-for-new-backer" data-text="<%=current_user.id%>" >
    <h5 id="add-backer-title"> Add a Backer</h5>
    <%= form_tag(:method => "get") do %>
      <div class="input-group mb-3">
        <%= text_field_tag :f_name, params[:f_name], placeholder: "First Name", class: 'form-control' %>
        <%= text_field_tag :l_name, params[:l_name], placeholder: "Last Name", class: 'form-control'  %>
        <div class="input-group-append">
          <%= submit_tag "Search", :name => nil, class: 'btn btn-outline-secondary', type: 'button', id: "find-backer-by-name" %>
        </div>
      </div>
    <% end %>

  <%= form_tag({controller: "search", action: "index"}, method: "get") do %>
      <div class="input-group mb-3">
        <%= email_field_tag :email, params[:email], placeholder: "Email", class: 'form-control' %>
        <div class="input-group-append">
          <button class="btn btn-outline-secondary" type="button" id="invite-backer-button">Invite!</button>
        </div>
      </div>
  <% end %>

</div>

app/views/dashboard/_add_dater.html.erb
 <div class="search-for-new-dater" data-text="<%=current_user.id%>" >
  <h5 id ='new-dater-title'>Or add a new dater below</h5>

   <%= form_tag(:method => "get") do %>
    <div class="input-group mb-3">
      <%= text_field_tag :f_name, params[:f_name], placeholder: "First Name", class: 'form-control' %>
      <%= text_field_tag :l_name, params[:l_name], placeholder: "Last Name", class: 'form-control'  %>
      <div class="input-group-append">
        <%= submit_tag "Search", :name => nil, class: 'btn btn-outline-secondary', type: 'button', id: "find-dater-by-name" %>
      </div>
    </div>
   <% end %>

  <%= form_tag({controller: "search", action: "index"}, method: "get") do %>
    <div class="input-group mb-3">
    <%= email_field_tag :email, params[:email], placeholder: "Email", class: 'form-control' %>
      <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="button" id="invite-dater-button">Invite</button>
      </div>
    </div>
  <% end %>



</div>

app/views/dashboard/_backer_tab.html.erb
<div class = 'backer-tab-container'>
  <ul class="pagination  ">
    <li class="page-item ">
      <a class="page-link backer-table-striped" id='backer-tab-active' >Backers</a>
    </li>
    <li class="page-item"><%= link_to 'Daters', dashboard_path(current_user,tab:'dater'),class:'page-link', id:'dater-tab-not-active'%></li>
  </ul>
</div>
<div class="card-body backer-tab-body">
  <div class = 'backer-tab-header col-md-8'>
    <h4>Welcome to the backer area. Here you can help your daters find a mate or search for new daters</h4>
  </div>
  <table class="table table-striped">
  <thead>
    <tr class= 'backer-table-striped'>
      <td scope="col">Dater</td>
      <td scope="col">Percent Complete</td>
      <td scope="col">Answer Questions about your dater</td>  
      <td scope="col">Find a mate for them</td>
    </tr>
  </thead>
  <tbody>
    <% current_backer.daters.each  do |dater|%>
    <tr class='backer-table-row'>
      <td > <%= link_to image_tag(dater.user.image.url), users_path(dater), id:'dater-img-td'%></td>
      <td>50%</td>
      <td><%= link_to 'Questions', new_backer_dater_comment_path(current_user, dater), class:'btn-primary btn-sm',id:'d-q-button'%></td>
      <td><%= link_to 'Find their mate', users_path(dater), class:'btn-primary btn-sm',id:'find-mate-for-backer'%></td>
    </tr>
    <% end %>     
    </tbody>
  </table>
  <%= render 'add_dater'%>
</div>  

app/views/dashboard/_dash_side.html.erb
<div class='card card-profile text-center col-md-2' id='dash-side' >
  <div class = 'card-header' id = 'dash-side-header'> You</div>
  <img alt='' class='card-img-top' src='https://s3.amazonaws.com/pytdating/andrea-reiman-417352-unsplash.jpg'>
  <div class='card-block'>
    <% if current_user.image %>
      <%= image_tag current_user.image.url, class:'card-img-profile' %>
    <% end %>
    <div class='card-title'>
      <h6> <%= current_user.f_name%> </h6><br>
      <p> <%= current_user.l_name%></p> <br>
      <h6>Location</h6><br>
      <p><%= ZipCodes.identify("#{current_user.daters.first.trait.zip}")[:city]%></p>
    </div>
  </div>
</div>

app/views/dashboard/_dater_tab.html.erb
<div class = 'dater-tab-container'>
  <ul class="pagination  ">
    <li class="page-item ">
    <%= link_to 'Backers', dashboard_path(current_user,tab:'backer'),class:'page-link', id:'backer-tab-not-active'%>
    </li>
      <a class="page-link backer-table-striped" id='dater-tab-active' >Daters</a>
    <li class="page-item"></li>
  </ul>
</div>
<div class="card-body dater-tab-body">
  <div class = 'dater-tab-header col-md-8'>
    <h4>Welcome to the dater area! Here you can check out your pool and manage your backers</h4>
  </div>

    <div class = 'dater-tab-buttons'>
      <a class =" " id="pool-button"> Checkout your pool</a>
      <a class =" "id="list-backer-button">Check out you backers</a>
      <%= render 'pool'%>
      <%= render 'list_backer'%>
    </div>
</div>  

app/views/dashboard/_list_backer.html.erb
    <div class = "list-and-add-backers">
    <table class=" table table-striped">
    <h5 id="dater-table-header">Your backers</h5>
    <thead>
      <tr class= 'dater-table-striped'>
        <td>Backer</td>
        <td>Name</td>
        <td>Contact</td>
      </tr>
    </thead>
    <tbody>
    <% current_dater.backers.each do |backer|%>
      <tr>
       <td><%= link_to image_tag(backer.user.image.url), users_path(backer), id:'dater-img-td'%></td>
       <td><%= backer.f_name%></td>
       <td><%=link_to 'Message', new_conversation_path(recipient: backer), class:"", id:'message-backer' %></td>
      </tr>
    <% end %>     
    </tbody>
  </table>
    <%= render 'add_backer'%>
    </div>

app/views/dashboard/_match_preferences.html.erb
<div class="match-preferences" >
<table class="table table-striped" id='traits-table'>
<thead>
  <tr>
    <th scope="col">Trait</th>
    <th scope="col">Preference</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>Smoker</td>
    <td></td>
  </tr>
  <tr>
  <td>Smoker</td>
  <td></td>
</tr>
</tbody>
</table>
</div>

app/views/dashboard/_pool.html.erb
<div class="show-the-daters-backers" >
  <% if current_dater.pool.empty? %>

    <div class="alert alert-warning" role="alert" id="pool-is-empty">
      <h4 class="">Your Dating Pool is Empty!</h4>
      <p>Message your Backers! Tell them to pull it together and find you a date!</p>
   </div>

  <% else %>
    <div id='gallery-cards-container'>
    <% current_dater.pool.each do |match| %>
            <div class="card dater-card">
            <% if current_user.image %>
            <%= link_to image_tag(match.first.user.image.url, class:'card-img-top'), user_path(match.first.user) %>
            <% end %>
                <div class="card-body"id="card-body" >
                    <h5 class="card-title" id="card-body"><%= match[0].f_name %></h5>
                </div>
            </div>
        <% end %>
    </div>
    <% end%>
</div>

app/views/dashboard/_visitor_profile_side.html.erb
<div class='card  card-profile text-center col-md-2' id='dash-side' >
  <div class = 'card-header'><%= @dater.f_name %></div>
  <img alt='' class='card-img-top' src='https://s3.amazonaws.com/pytdating/andrea-reiman-417352-unsplash.jpg'>
  <div class='card-block'>
         <% if @dater.user.image %>
              <%= image_tag @dater.user.image.url, class:'card-img-profile' %>
            <% end %>
    <h4 class='card-title'>
    <%= @dater.f_name%>    
    </h4>
      <div class="card-body ">
      <table class = 'table table-striped'>
      <thead>
      </thead>
      <tbody>
        <tr><td>Smoking</td></tr>
        <%if @dater.trait.smoker == 'dont_care'%>
            <tr><td>doesn't smoke</td></tr>
        <%else%>
            <tr><td><%= @dater.trait.smoker%></td></tr>
        <%end%> 
        <tr><td>Drinking</td></tr>
        <tr><td><%= @dater.trait.alcohol%></td></tr>
        <tr><td>Gender</td></tr>
        <tr><td><%= @dater.trait.gender%></td></tr>
        <tr><td>Body Type</td></tr>
        <%if @dater.trait.body_type == 'any'%>
            <tr><td>
            Decline to answer
            </tr></td>
        <%else%>
            <tr><td><%= @dater.trait.smoker%></td></tr>
        <%end%> 
        <tr><td>Religiosity</td></tr>
        <tr><td><%= @dater.trait.religiosity%></td></tr>
        <tr><td>Religion</td></tr>
        <tr><td><%= @dater.trait.religion%></td></tr>
        <tr><td>ethnicity</td></tr>
        <tr><td><%= @dater.trait.ethnicity%></td></tr>
        </tbody>
      </table>
        
      </div>

  </div>
</div>

app/views/dashboard/show.html.erb
<%=render 'dash_side'%>
<% if params['tab'] = 'backer' && params['tab'] != 'dater' %>
  <div class = 'col-md-offset-1 col-md-9 card text-center' id= 'dash-body'>
    <div class= 'card-header backer-table-striped'><h6> Backer's Dashboard</h6></div>
    <%= render 'backer_tab' %>
  </div>
<% else %>
  <div class = 'col-md-offset-1 col-md-9 card text-center' id= 'dash-body'>
    <div class= 'card-header dater-table-striped'><h6> Dater's Dashboard</h6></div>
      <%= render 'dater_tab'%>
  </div>
<% end %>