config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/invites', to: 'invites#show'
  root to: "homes#show"

  resources :sessions, only: [:create, :destroy]
  resource :homes, only: [:show]
  resources :search, only: [:index]
  resource :mate_preference, only: [:update]
  resource :trait, only: [:update]

  resources :conversations do
    resources :messages
   end

   resources :daters do 
    resources :images
  end
  resources :dashboard

  resources :backers do
    resources :daters do
          resources :comments,  as: 'comments'
          resources :personalities
    end
  end

  resources :users
  post 'search', to: 'search#create' , as: "search"

  get 'user/:id/pool', to: 'pool#index' , as: "user_pool"
  put 'user/:id/pool', to: 'pool#update' , as: "edit_user_pool"


  namespace :api do
    namespace :v1 do

      resources :users, only: [:index, :show]

      resources :daters, only: [:index, :show]
      namespace :daters do
        get "/:id/backers", to: "backers#index"
        get "/:id/backers/:backer_id", to: "backers#create"
        # post "/meals/:meal_id/foods/:id", to: "meals#create", as: :meal_foods
      end

      resources :backers, only: [:index, :show]
      namespace :backers do
        get "/:id/daters", to: "daters#index"
      end

    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

    def index
      @conversations = current_user.mailbox.conversations.paginate(:page => params[:page], :per_page => 10)
    end
  
    def new
      @recipient = User.find(params[:recipient])
    end
  
    def create
      recipient = User.find(params[:format])
      receipt = current_user.send_message(recipient, params[:body], params[:subject])
      flash[:notice] = "Message Sent"
      redirect_to conversation_path(receipt.conversation)
    end
  
    def show
      @conversation = current_user.mailbox.conversations.find(params[:id])
        receiver = current_user.mailbox.conversations.find(params[:id]).receipts.where.not(receiver_id: current_user.id).first.receiver_id 
      @conversations = current_user.mailbox.receipts.select  do |receipt|
          receipt.conversation.receipts.find_by(receiver_id: receiver)
      end
    end
    
  
  end
  

app/views/conversations/index.html.erb
<%= render 'dashboard/dash_side'%>
  <div class="col-md-offset-2 col-md-8 card " id='message-list-container' >
    <div class = 'card-header'>Your Conversations</div>
    <table class="table table-striped" id= 'message-list' >
        <tr>
          <th >User</th>
          <th >Subject</th>
          <th >Date</th>
        </tr>
        <% @conversations.each do |conversation| %>
        <tr >
          <td> <%= User.find( conversation.receipts.where.not(receiver_id:current_user.id).first.receiver_id).f_name %></td>
          <td> <%= link_to conversation.subject, conversation_path(conversation) %></td>
          <td> <%= conversation.updated_at.strftime('%m-%d-%y') %></td>
        </tr>
        <% end %>
    </table>  
  </div>
</div>









  

app/views/conversations/new.html.erb
<%= render 'dashboard/dash_side'%>
<div id = "convo-container">
  <div class="card" id="">
    <div class = 'card-header'>New Conversation with   <%= @recipient.f_name %></div>
      <%= form_tag conversations_path(@recipient), method: :post do %>
      <div class="card-body">
          <p class="card-text"><%= label_tag :subject %></p>
          <%= text_field_tag :subject, nil, placeholder: "Subject", class:"input-search" %>
          <p><%= label_tag :body %></p>
          <%= text_area_tag :body, nil, placeholder: "Message" %>
          <p><%= submit_tag "Send Message", class: "primary-btn btn-md" %></p>
      <% end %>
      </div>
      </div>
    </div>

app/views/conversations/show.html.erb
  
<%= render 'dashboard/dash_side'%>
<div class ='col-md-offset-1 col-md-10'>
  <div class = 'message-show-container'>
    <%@conversations.each do |receipt| %>
    <div class="card col-md-4" id="message-card">
      <div class="card-header"> <%= receipt.message.subject %></div>
      <div class="card-body"id="">
          <p class="card-text"> <%= receipt.message.body %></p>
      </div>
      <%= button_to 'Delete', conversation_message_path(params[:id],receipt.id), method: :delete, class:'primary-btn btn', id:'delete-message' %>  
    </div>
    <% end %>
  </div>
  <div class="card col-md-3" id="new-message">
    <div class="card-header">New Message </div>
    <%= form_tag conversation_messages_path(@conversation) ,method: :post do  %>
      <div class="card-body ">
          <p class="card-text"><%= label_tag :subject %></p>
          <p><%= text_field_tag :subject,nil, class:'form-control' %></p>
          <p><%= label_tag :body %></p>
          <p><%= text_area_tag :body,nil, class:'form-control' %></p>
          <p><%= submit_tag "Send Message", class: "primary-btn btn-md" %></p>
      </div>
    <% end %>
  </div>    
</div>
  