config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/invites', to: 'invites#show'
  root to: "homes#show"

  resources :sessions, only: [:create, :destroy]
  resource :homes, only: [:show]
  resources :search, only: [:index]
  resource :mate_preference, only: [:update]
  resource :trait, only: [:update]

  resources :conversations do
    resources :messages
   end

   resources :daters do 
    resources :images
  end
  resources :dashboard

  resources :backers do
    resources :daters do
          resources :comments,  as: 'comments'
          resources :personalities
    end
  end

  resources :users
  post 'search', to: 'search#create' , as: "search"

  get 'user/:id/pool', to: 'pool#index' , as: "user_pool"
  put 'user/:id/pool', to: 'pool#update' , as: "edit_user_pool"


  namespace :api do
    namespace :v1 do

      resources :users, only: [:index, :show]

      resources :daters, only: [:index, :show]
      namespace :daters do
        get "/:id/backers", to: "backers#index"
        get "/:id/backers/:backer_id", to: "backers#create"
        # post "/meals/:meal_id/foods/:id", to: "meals#create", as: :meal_foods
      end

      resources :backers, only: [:index, :show]
      namespace :backers do
        get "/:id/daters", to: "daters#index"
      end

    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :image
  mount_uploader :image, ImageUploader,

  :mount_on => :image
  has_many :daters
  has_many :backers
  has_many :dater_backers, through: :daters
  has_many :dater_backers, through: :backers
  has_one :mate_preference

  acts_as_messageable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.auth_name = auth.info.name
      user.f_name = auth.info.first_name
      user.l_name = auth.info.last_name
      user.email = auth.info.email
      user.remote_image_url =  "https://s3.amazonaws.com/pytdating/avatardefault.jpg"
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
      Dater.find_or_create_by(user_id: user.id, f_name:user.f_name, l_name:user.l_name,image_1: user.remote_image_url)
      Backer.find_or_create_by(user_id: user.id, f_name: user.f_name, l_name: user.l_name,image_1: user.remote_image_url)
      MatePreference.find_or_create_by(dater_id: user.id)
      Trait.find_or_create_by(dater_id: user.id, zip:80203)
    end
  end
  

  def mailboxer_email(object)
    return object
  end


end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    if params[:email]
      render json: User.find_by(email: params[:email])
    elsif params[:f_name]
      render json: User.where(f_name: params[:f_name], l_name: params[:l_name])
    else
    render json: User.all
    end
  end

  def show
    render json: User.find(current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  def index
    @daters = SearchService.new.search(params,current_user)
    if params[:format]
      @searching_for = Dater.find(params[:format])
    end
  end

  def create
  end

  def edit
    @user  = current_user
  end

  def update
    user  = current_user
    user.update(user_params)
    redirect_to user_path(user)
  end

  
  def show
    @user = User.find(params[:id])
    @dater = @user.daters.first
  end


  def user_params
    params.require(:user).permit(:f_name, :l_name, :image)
  end

end
  

app/views/users/_current_user_show.html.erb
<%= render 'dashboard/dash_side'%>
<div class = 'user-container'>
    <p>Welcome <%= current_user.f_name%>!</p>
    <div class="card profile-card" id = 'about-you'>
        <div class="card-header">About You</div>
        <div class="card-body">
            <% if current_dater.trait.other.empty?%>
                <p class="card-text">Tell people about yourself!</p>
            <%else %>
                <p class="card-text"><%= current_dater.trait.other%></p>
            <%end%>
        </div>
        <%= link_to 'Edit',nil, class:"primary-btn ",id: "edit-about-button"  %>
       <div class = 'about-you'>
            <%= form_for @dater.trait do |f| %>
                <p>  <%= f.text_area :other, class:'form-control'%></p>
                 <%= f.submit "Update" , class: "primary-btn" %>
            <% end %>
        </div>
    </div>
     <%= render 'q_1_modal'%>
    <div class="card profile-card">
        <div class="card-header">
            What your backers say about you
        </div>
        <%= render 'list-questions'%>
    </div>
      <%= link_to 'Edit your profile',nil, class:"primary-btn btn-md", id:"edit-profile-button" %>
      <%= link_to 'Edit your mate preference',nil, class:"primary-btn btn-md",id:"edit-mate-button"  %>
    <div class = 'edit-profile-container'>
        <div class="card profile-card edit-profile">
            <div class="card-header">
                Edit Your Profile
            </div>
            <%= form_for @user do |f| %>
                <p>  <%= f.label :First_Name %></p>
                <p>  <%= f.text_field :f_name, class:'form-control'%></p>
                <p>  <%= f.label :Last_Name %></p>
                <p>  <%= f.text_field :l_name, class:'form-control'%></p>
                <p>  <%= f.label :Image %></p>
                <p>  <%= f.file_field :image, class:'form-control'%></p>
                <p>  <%= f.submit "Update" , class: "primary-btn btn-md" %></p>
            <% end %>
        </div>
        <%= render 'edit_mate_prefs'%>
        <%= render 'edit_traits'%>        
    </div>
</div>

app/views/users/_dater-answer1-list.html.erb
<div class = 'answer1-table col-md-12 collapse' id= "answer1Collapse">
    <table class = 'table table-striped '>
        <thead>
            <tr>
                <th scope="col">Commenter</th>
                <th scope="col">Comment</th>        
            </tr>
        </thead>
        <tbody>
            <% @dater.comments.where(question_id:1).each do  |comment|%>
            <tr>
                <td><%= Backer.find(comment.backer_id).f_name%></td>
                <td><%= comment.comment %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/users/_dater-answer3-list.html.erb
<div class = 'answer3-table col-md-12'>
    <table class = 'table table-striped '>
        <thead>
        <tr>
            <th scope="col">Commenter</th>
            <th scope="col">Comment</th>        
        </tr>
        </thead>
        <tbody>
            <% current_dater.comments.where(question_id:3).each do  |comment|%>
                <tr>
                <td><%= Backer.find(comment.backer_id).f_name%></td>
                <td><%= comment.comment %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/users/_dater-answer4-list.html.erb
<div class = 'answer4-table col-md-12'>
    <table class = 'table table-striped '>
        <thead>
      <tr>
        <th scope="col">Commenter</th>
        <th scope="col">Comment</th>        
      </tr>

    </thead>
<tbody>
<% current_dater.comments.where(question_id:4).each do  |comment|%>
    <tr>
    <td><%= Backer.find(comment.backer_id).f_name%></td>
    <td><%= comment.comment %></td>
    </tr>
<% end %>
</tbody>
    </table>
</div>

app/views/users/_edit_mate_prefs.html.erb
        <div class="card profile-card edit-mate-preference">
            <div class="card-header">
                Edit Your Mate Preferences 
            </div>
                <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Trait</th>
                <th scope="col">Selection</th>
            </tr>
            </thead>
            <tbody>
        <%= form_for @dater.mate_preference do |f| %>
             <tr>
                <td><%= f.label :min_height %></td>
                <td>
                    <%=  number_field_tag "min_height_ft", nil, in: 4...10, id: 'number-input', value:"#{current_dater.mate_preference.min_height/12}",  :style => 'backgound-color: green' %> ft
                    <%= number_field_tag "min_height_in", nil, in: 0...12, id: 'number-input', value:"#{current_dater.mate_preference.min_height%12}" %> in 
                </td> 
            </tr>
             <tr>
                <td><%= f.label :max_height %></td>
                <td>
                    <%=  number_field_tag "max_height_ft", nil, in: 4...10, id: 'number-input', value:"#{current_dater.mate_preference.max_height/12}"%> ft
                    <%= number_field_tag "max_height_in", nil, in: 0...12, id: 'number-input', value:"#{current_dater.mate_preference.max_height/12}" %> in 
                </td> 
            </tr>
            <tr>
                 <td><%= f.label :smoker %></td>
                 <td><%= f.select :smoker, MatePreference.smokers.map { |key, value| [key.humanize, key] }, class: "btn btn-secondary dropdown-toggle", id:"dropdownMenu2", class:" form-control"%></td>
            </tr>
            <tr>
                 <td><%= f.label :religiosity %></td>
                 <td><%= f.select :religiosity, MatePreference.religiosities.map { |key, value| [key.humanize, key] }, class: "btn btn-secondary dropdown-toggle", id:"dropdownMenu2"%></td>
            </tr>
            <tr>
                 <td><%= f.label :religion %></td>
                 <td><%= f.select :religion, MatePreference.religions.map { |key, value| [key.humanize, key] }, class: "btn btn-secondary dropdown-toggle", id:"dropdownMenu2"%></td>
            </tr>
            <tr>
                <td><%= f.label :alcohol %></td>
                <td><%= f.select :alcohol, MatePreference.alcohols.map { |key, value| [key.humanize, key] },{class:" form-control"} %></td>
            </tr>
            <tr>
                <td> <%= f.label :body_type %></td>
                <td><%= f.select :body_type, MatePreference.body_types.map { |key, value| [key.humanize, key] } %></td>
            </tr>
          <tr>
                <td> <%= f.label :has_kids %></td>
                <td><%=  f.select :has_kids, [['No Kids', false], ['Has Kids', true]]%></td>
            </tr>
            <tr>
                <td> <%= f.label :wants_kids %></td>
                <td><%= f.select :wants_kids, MatePreference.wants_kids.map { |key, value| [key.humanize, key] } %></td>
            </tr>
            <tr>
                <td> <%= f.label :education %></td>
                <td><%= f.select :education, [['Not a college Grad', false], ['Collage Grad', true]] %></td>
            </tr>
            <tr>
                 <td><%= f.label :politicalness %></td>
                 <td><%= f.select :politicalness, MatePreference.politicalnesses.map { |key, value| [key.humanize, key] }, class: "btn btn-secondary dropdown-toggle", id:"dropdownMenu2"%></td>
            </tr>
            <tr>
                <td> <%= f.label :political_leaning %></td>
                <td><%= f.select :political_leaning, MatePreference.political_leanings.map { |key, value| [key.humanize, key] } %></td>
            </tr>
            <tr>
                <td> <%= f.label :zip_radius %></td>
                <td> <%= f.number_field "zip_radius", in: 1...100, id: 'number-input'%> </td>
            </tr>
            <tr>
                <td><%= f.label :has_pets %></td>
                <td><%= f.select :has_pets, MatePreference.has_pets.map { |key, value| [key.humanize, key] } %></td>
                </tr>            
            <tr>
                <td> <%= f.label :orientation %></td>
                <td><%= f.select :orientation, MatePreference.orientations.map { |key, value| [key.humanize, key] } %></td>
            </tr>
            <tr>
                <td><%= f.label :gender %></td>
                <td><%= f.select :gender, MatePreference.genders.map { |key, value| [key.humanize, key] } %></td>
                </tr>            
    </tbody>
  </table>
              <%= f.submit "Update" , class: "primary-btn btn-md" %>
        <% end %>
        </div>

app/views/users/_edit_traits.html.erb
        <div class="card profile-card edit-traits">
            <div class="card-header">
                Your Traits
            </div>
                <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Trait</th>
                <th scope="col">Selection</th>
            </tr>
            </thead>
            <tbody>
        <%= form_for @dater.trait do |f| %>
             <tr>
                <td><%= f.label :height %></td>
                <td>
                    <%=  number_field_tag "height_ft", nil, in: 4...10, id: 'number-input', value:"#{current_dater.trait.height/12}"%> ft
                    <%= number_field_tag "height_in", nil, in: 0...12, id: 'number-input', value:"#{current_dater.trait.height%12}" %> in 
                </td> 
            </tr>
            <tr>
                 <td><%= f.label :smoker %></td>
                 <td><%= f.select :smoker, Trait.smokers.map { |key, value| [key.humanize, key] }, class: "btn btn-secondary dropdown-toggle form-control", id:"dropdownMenu2"%></td>
            </tr>
            <tr>
                 <td><%= f.label :religiosity %></td>
                 <td><%= f.select :religiosity, Trait.religiosities.map { |key, value| [key.humanize, key] }, {class: "btn-sm form-control"}%></td>
            </tr>
            <tr>
                 <td><%= f.label :religion %></td>
                 <td><%= f.select :religion, Trait.religions.map { |key, value| [key.humanize, key] },  {class: "btn-sm form-control"}, id:"dropdownMenu2"%></td>
            </tr>
            <tr>
                <td><%= f.label :alcohol %></td>
                <td><%= f.select :alcohol, Trait.alcohols.map { |key, value| [key.humanize, key] } %></td>
            </tr>
            <tr>
                <td> <%= f.label :body_type %></td>
                <td><%= f.select :body_type, Trait.body_types.map { |key, value| [key.humanize, key] } %></td>
            </tr>
          <tr>
                <td> <%= f.label :has_kids %></td>
                <td><%=  f.select :has_kids, [['No Kids', false], ['Has Kids', true]]%></td>
            </tr>
            <tr>
                <td> <%= f.label :wants_kids %></td>
                <td><%= f.select :wants_kids, [['Eww', false], ['BABEEZ', true]] %></td>
            </tr>
            <tr>
                <td> <%= f.label :education %></td>
                <td><%= f.select :education, [['Not a college Grad', false], ['Collage Grad', true]] %></td>
            </tr>
            <tr>
                 <td><%= f.label :politicalness %></td>
                 <td><%= f.select :politicalness, Trait.politicalnesses.map { |key, value| [key.humanize, key] }, class: "btn btn-secondary dropdown-toggle", id:"dropdownMenu2"%></td>
            </tr>
            <tr>
                <td> <%= f.label :political_leaning %></td>
                <td><%= f.select :political_leaning, Trait.political_leanings.map { |key, value| [key.humanize, key] } %></td>
            </tr>
            <tr>
                <td> <%= f.label :zip %></td>
                <td> <%= f.number_field "zip", id: 'number-input'%> </td>
            </tr>
            <tr>
                <td><%= f.label :has_pets %></td>
                <td><%= f.select :has_pets, [['No Pets', false], ['Yes Pets', true]] %></td>
                </tr>            
            <tr>
                <td> <%= f.label :orientation %></td>
                <td><%= f.select :orientation, Trait.orientations.map { |key, value| [key.humanize, key] } %></td>
            </tr>
            <tr>
                <td><%= f.label :gender %></td>
                <td><%= f.select :gender, Trait.genders.map { |key, value| [key.humanize, key] } %></td>
                </tr>            
            </tbody>
        </table>
              <%= f.submit "Update" , class: "primary-btn btn-md" %>
        <% end %>
        </div>

app/views/users/_list-questions.html.erb
<div class="" id="answer-card">
    <button class="dater-answer-button primary-btn" data-toggle="collapse" role="button" aria-expanded="false" id='dater-q1-button' aria-controls="collapseExample">       
    <%="#{Question.first.question}"%>
    </button>
    <%= render 'dater-answer1-list'%>
    <button class="dater-answer-button primary-btn" data-toggle="collapse" role="button" aria-expanded="false" id='dater-q2-button' aria-controls="collapseExample">       
    <%="#{Question.second.question}"%>
    </button>
    <%= render 'dater-answer2-list'%>
    <button class="dater-answer-button primary-btn" data-toggle="collapse" role="button" aria-expanded="false" id='dater-q3-button' aria-controls="collapseExample">       
    <%="#{Question.third.question}"%>
    </button>
    <%= render 'dater-answer3-list'%>
    <button class="dater-answer-button primary-btn" data-toggle="collapse" role="button" aria-expanded="false" id='dater-q4-button' aria-controls="collapseExample">       
    <%="#{Question.find(4).question}"%>
    </button>
    <%= render 'dater-answer4-list'%>
    <button class="dater-answer-button primary-btn" data-toggle="collapse" role="button" aria-expanded="false" id='dater-q5-button' aria-controls="collapseExample">       
    <%="#{Question.find(5).question}"%>
    </button>
    <%= render 'dater-answer5-list'%>
</div>

app/views/users/_q_1_modal.html.erb
<div class = 'col-md-offset-4 col-md-4 q_1_modal'>
    <%= form_for @dater.trait do |f| %>
        <p>  <%= f.label :What_is_you_favorite_food_processor?, class:'form-control'%></p>
        <p>  <%= f.text_area :other, class:'form-control'%></p>
        <p>  <%= f.submit "Update" , class: "primary-btn btn-md" %></p>
    <% end %>
</div>

app/views/users/_search_for_filter.html.erb
        <div class="card card-profile col-md-2" id="filter-table">
            <div class="card-header">
               <p>Filter</p>
               <p>(autpopulated with <%= @searching_for.f_name%>'s preferences)</p>
            </div>
            <table class="table table-striped" >
            <tbody>
            <%= form_tag( '/users/', :method => :get ) do %>
             <tr>
                <td><%= label_tag :political_leaning %></td>
            </tr>
            <tr>
                <td id="select"> <%= select_tag :political_leaning, options_for_select(MatePreference.political_leanings.map {|k, v| [k.humanize.capitalize, v]},@searching_for.mate_preference.political_leaning), {class: " btn-sm form-control"} %></td>
            </tr>
             <tr>
            <td><%= label_tag :politicalness%></td>
            </tr>
            <tr>
                <td> <%= select_tag :politicalness, options_for_select(MatePreference.politicalnesses.map {|k, v| [k.humanize.capitalize, v]}, @searching_for.mate_preference.politicalness.humanize), {class: " btn-sm form-control"} %></td>
            </tr>
             <tr>
                <td><%= label_tag :smoker%></td>
            </tr>
            <tr>
                <td> <%= select_tag :smoker, options_for_select(MatePreference.smokers.map {|k, v| [k.humanize.capitalize, v]},:selected => @searching_for.mate_preference.smoker), {class: "form-control"} %></td>
            </tr>
             <tr>
                <td><%= label_tag :alcohol%></td>
            </tr>
            <tr>
                <td> <%= select_tag :alcohol, options_for_select(MatePreference.alcohols.map {|k, v| [k.humanize.capitalize, v]},@searching_for.mate_preference.alcohol), {class: " btn-sm form-control"} %></td>
            </tr>
             <tr>
                <td><%= label_tag :body_type%></td>
            </tr>
            <tr>
                <td> <%= select_tag :body_type, options_for_select(MatePreference.body_types.map {|k, v| [k.humanize.capitalize, v]},@searching_for.mate_preference.body_type) , {class: " btn-sm form-control"}%></td>
            </tr>
             <tr>
                <td><%= label_tag :religiosity%></td>
            </tr>
            <tr>
                <td> <%= select_tag :religiosity, options_for_select(MatePreference.religiosities.map {|k, v| [k.humanize.capitalize, v]}, @searching_for.mate_preference.religiosity), {class: " btn-sm form-control"} %></td>
            </tr>
             <tr>
                <td><%= label_tag :orientation%></td>
            </tr>
            <tr>
                <td> <%= select_tag :orientation, options_for_select(MatePreference.orientations.map {|k, v| [k.humanize.capitalize, v]}, @searching_for.mate_preference.orientation), {class: " btn-sm form-control"} %></td>
            </tr>
             <tr>
                <td><%= label_tag :religion%></td>
            </tr>
            <tr>
                <td> <%= select_tag :religion, options_for_select(MatePreference.religions.map {|k, v| [k.humanize.capitalize, v]}, @searching_for.mate_preference.religion), {class: " btn-sm form-control"} %></td>
            </tr>
            </tbody>
        </table>
              <%= submit_tag "Update" , class: "primary-btn btn-md" %>
        <% end %>
    </div>

app/views/users/_searching_for.html.erb
<div class="container  col-md-4">
      <div class = 'card text-center searching-for ' id= ''>
        <div class = 'card-header'id='searching-for-header'>You are looking for a mate for <%= @searching_for.f_name %></div>
          <div class = 'card-body' id='searching-for-body'>       
            <p><%= @searching_for.f_name%></p>
            <% if @searching_for.user.image %>
              <%= link_to image_tag(@searching_for.user.image.url), user_path(@searching_for.user.id, class:'card-img-profile') %>
            <% end %>
            <p><%= ZipCodes.identify("#{@searching_for.trait.zip}")[:city]%></p>
          </div>
        </div>
  </div>
</div>

app/views/users/_show_dater_traits.html.erb
        <div class="card profile-card show-traits">
            <div class="card-header">
                This dater's Traits
            </div>
                <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Trait</th>
                <th scope="col">Feels</th>
            </tr>
            </thead>
            <tbody>
             <tr>
                <td> Height</td>
                <td>
                    <%= @user.daters.first.trait.height/12%> ft
                    <%= @user.daters.first.trait.height%12%> in
                </td> 
            </tr>
            <tr>
                 <td> Smoker</td>
                 <td><%= @user.daters.first.trait.smoker %></td>
            </tr>
            <tr>
                 <td> Religiosity</td>
                 <td><%= @user.daters.first.trait.religiosity%></td>
            </tr>
            <tr>
                 <td> Religion</td>
                 <td><%= @user.daters.first.trait.religion%></td>
            </tr>
            <tr>
                <td> Relationship to alcohol</td>
                 <td><%= @user.daters.first.trait.alcohol%></td>
            </tr>
            <tr>
                <td> Body Type</td>
                 <td><%= @user.daters.first.trait.body_type%></td>
            </tr>
            <tr>
                <td> Kids</td>
                 <td><%= @user.daters.first.trait.has_kids%></td>
            </tr>
            <tr>
                <td>  Feelings about kids </td>
                 <td><%= @user.daters.first.trait.wants_kids%></td>
            </tr>
            <tr>
                <td>  Education </td>
                 <td><%= @user.daters.first.trait.education%></td>
            </tr>
            <tr>
                <td>  Feels about politics </td>
                 <td><%= @user.daters.first.trait.politicalness%></td>
            </tr>
            <tr>
                <td>  Poltical Leanings</td>
                 <td><%= @user.daters.first.trait.political_leaning%></td>
            </tr>
            <tr>
                <td> ZipCode</td>
                 <td><%= @user.daters.first.trait.zip%></td>  
            </tr>
            <tr>
                <td> Pets</td>
                 <td><%= @user.daters.first.trait.has_pets%></td>  
                </tr>            
            <tr>
                <td>  Sexual Orientation</td>
                 <td><%= @user.daters.first.trait.orientation%></td>  
            </tr>
            <tr>
                <td>Gender </td>
                 <td><%= @user.daters.first.trait.gender%></td>  
                </tr>            
            </tbody>
        </table>
        </div>
    </div>

app/views/users/_visitor_user_show.html.erb
<%=render 'dashboard/visitor_profile_side'%>
<div class = 'user-parent col-md-6'>
    <div class = 'user-container'>
        <div class="card profile-card">
            <div class="card-header">
                <%= @dater.f_name %>
                <%= @dater.l_name %>
            </div>
            <div class="card-body">
                <h5 class="card-title">Location</h5>
                <p class="card-text"><%= ZipCodes.identify("#{@dater.trait.zip}")[:city] %></p>
            </div>
        </div>
        <div class="card profile-card">
            <div class="card-header">About</div>
            <div class="card-body"><%="#{Faker::Hobbit.quote}"%></div>
        </div>
        <div class="card profile-card">
            <div class="card-header">
                What <%=@dater.f_name%>'s backers say about them
            </div>
            <%= render 'list-questions'%>
        </div>
    </div>
</div>
<div class = 'user-right-side'>
    <%= link_to 'Send Message', new_conversation_path(recipient: @user), class:"primary-btn btn-md" %>
    <% if params[:searching_for] %>
        <%= link_to "Add to your dater's pool", edit_user_pool_path(@user, searching_for: params[:searching_for]), method: :put, class:"primary-btn btn-md" %>       
    <% else %>
        <%= link_to 'Add to your pool', edit_user_pool_path(@user), method: :put, class:"primary-btn btn-md" %>
    <% end %>
    <div class = 'personality-stats-show'>
        <h5>How <%=@dater.f_name%>'s backers rate them</h5>
        <% Personality.traits.each do |trait|%>
        <div class = 'slider-title'> <%=trait.to_s.capitalize%></div>
        <div class = 'parent-slider'>
            <div class = 'child-slider' style = 'width:<%= @dater.personality_avg(trait)%>%;background-color:<%= slider_colors.sample%>'></div>
        </div>
        <% end %>
    </div>
</div>  

app/views/users/index.html.erb
<% if params[:format]%>
    <%= render 'search_for_filter'%>
<%else%>
    <%= render 'filter'%>
<%end%>
    <div class=" col-md-9 card" id="gallery-container">
    <h5 class="card-header">All Daters</h5>
        <div id='gallery-cards-container'>
        <% @daters.each do |dater| %>
            <div class="card dater-card">
                    <h5 class="card-header" id="card-body"><%= dater.f_name %></h5>
            <% if dater.user.image %>
            <% if params[:format] %>
                <%= link_to image_tag(dater.user.image.url, class:'card-img-top'), user_path(dater.id,searching_for: params[:format]) %>
            <% else %>
                <%= link_to image_tag(dater.user.image.url, class:'card-img-top'), user_path(dater.id) %>
            <% end %>
            <% end %>    
                <% if !dater.trait.zip.nil? %>
                    <p><%= ZipCodes.identify("#{dater.trait.zip}")[:city] %></p>
                <%end%>
                <div>
                    <a href="#" class="card-link"></a>
                </div>
            </div>
        <% end %>
        </div>
    </div>

app/views/users/show.html.erb
        <%if @user.id == current_user.id%>
            <%=render 'current_user_show'%>
        <%else%>
             <%=render 'visitor_user_show'%>
        <%end%>
     </div>