config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/invites', to: 'invites#show'
  root to: "homes#show"

  resources :sessions, only: [:create, :destroy]
  resource :homes, only: [:show]
  resources :search, only: [:index]
  resource :mate_preference, only: [:update]
  resource :trait, only: [:update]

  resources :conversations do
    resources :messages
   end

   resources :daters do 
    resources :images
  end
  resources :dashboard

  resources :backers do
    resources :daters do
          resources :comments,  as: 'comments'
          resources :personalities
    end
  end

  resources :users
  post 'search', to: 'search#create' , as: "search"

  get 'user/:id/pool', to: 'pool#index' , as: "user_pool"
  put 'user/:id/pool', to: 'pool#update' , as: "edit_user_pool"


  namespace :api do
    namespace :v1 do

      resources :users, only: [:index, :show]

      resources :daters, only: [:index, :show]
      namespace :daters do
        get "/:id/backers", to: "backers#index"
        get "/:id/backers/:backer_id", to: "backers#create"
        # post "/meals/:meal_id/foods/:id", to: "meals#create", as: :meal_foods
      end

      resources :backers, only: [:index, :show]
      namespace :backers do
        get "/:id/daters", to: "daters#index"
      end

    end
  end
end

app/views/layouts/_nav.html.erb
      <nav class="navbar navbar-expand-lg   col-md-12" id="main-nav">
            <div class = 'logo-div'>
                <%= link_to image_tag('https://s3.amazonaws.com/pytdating/pytlogo.png'), homes_path %>
            </div>
            <h4>Meddle</h4>
            <a class="navbar-brand" id='header-title'></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                    <%if current_user%>
                        <%=link_to 'Dashboard', dashboard_path(current_user)%>
                        <%=link_to 'All daters', users_path%>
                    </li>
                    <a class='media' href='/conversations'>
                        <i class="far fa-envelope fa-2x"></i>
                    </a>
                        <a class ='media' href=<%= "/users/#{current_user.id}"%>><i class="fas fa-user fa-2x"></i></a>
                    <%end%>
                </ul>
            </div>
            <div class = 'login' id='login'>
                <% if current_user %>
                   Hi <%= current_user.f_name %>
                    <%= link_to "Sign out", signout_path %>
                <% else %>
                    <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in", class:'' %>
                 <% end %>
            </div>
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>Meddle</title>
      <%= favicon_link_tag('https://s3.amazonaws.com/pytdating/favicon-32x32.png')%>
      <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
      <%= stylesheet_link_tag "application", media: "all"%>
      <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>    
    </head>
    <div class = 'layer'></div>
      <body class='col-md-12'>
        <%= render '/layouts/nav' %>
        <% if flash[:notice] %>
          <div class="notice"><%= flash[:notice] %></div>
        <% end %>
        <% if params[:format]%>
          <%= render 'searching_for'%>
        <%end%>
        <div class = 'main col-md-12 ' >
          <%= yield %>
        </div>
        <footer class= 'col-md-12' id="footer">
                <a class = 'media' href='http://www.github.com/zacharylandes'><i class="fab fa-github fa-2x" target="_blank"></a></i>
                <a class = 'media' href = "https://www.linkedin.com/in/zacharylandes/" > <i class="fab fa-linkedin fa-2x" target="_blank"></i></a>
			          <a class = 'media' href="mailto:zach.g.landes@gmail.com" target="_blank"><i class="fab fa-google fa-2x" target="_blank"></i></a>
                <a class = 'media' href = 'http://zacharylandes.github.io'><img src="https://s3-us-west-1.amazonaws.com/gedaride/iconwhite.png"  target="_blank"/></a>
         </footer>
      </body>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>  
  </html>